name: iOS Hybrid Automated Build Process

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name'
        required: true
        type: string
      release_notes:
        description: 'Release Notes'
        required: true
        type: string
        
env:
  XCODE_VERSION: '16.2' # Specify your Xcode version
  BUILD_DIRECTORY: 'Build' # The target directory for the IPA

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30 # Add timeout to prevent hanging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags
          
      - name: Install gdown (Google Drive Downloader)
        run: |
          pip install gdown
          
      - name: Download folder from Google Drive (Public)
        run: |
          # Example: Download a single file (replace with your Google Drive file ID)
          gdown --id "1zHtMxxJfKf1x73487Qv951U0qucp_b7a" --output "hacon.zip"
          
          # If it's a folder, you might need to zip it first on Google Drive
          unzip hacon.zip
          
          # Remove the ZIP file after extraction (cleanup)
          rm hacon.zip
          rm -rf __MACOSX # Remove any Mac-specific metadata directories
          
          # Verify download
          ls -lh
          
      - name: Verify files
        run: |
          ls -lh  # Check file sizes
          cd HAFASLib/HAFASLib.framework/
          ls -lh  # Check file sizes
          cd ../../ # Go back to the root directory

